### ISSUE TITLE
Unsure how to use, Akka 2.4.4

### ISSUE THREAD

**Issue by acjay** [dnvriend/akka-persistence-jdbc-serialization-json#1]
I'm using Akka Persistence in Akka 2.4.4, along with akka-persistence-jdbc. My application isn't (yet) high performance, and so we're more interested in being able to human-inspect the database than the high performance of Protobuf, at this stage.

My app was already working with akka-persistence-jdbc just fine, writing what appears to be binary data to the database. I created my own `Serializer` to write my events to JSON, but the data in the `mesage` still appeared to be binary. This makes sense, as the column is still `BYTEA` and the `PersistentRepr` is still using default serialization.

I installed this as indicated in the README, but the data appears to still be binary. I'm not sure whether I have everything fully configured yet. I have a few questions:
- Should I change the type in my database to something like `VARCHAR`?
- Do I need to configure `akka.serializers` and `akka.serialization-bindings` in a particular way to activate this project?
- Do I need to configure those for my own classes?
- Is this project compatible with Akka 2.4.x?

**Comment by acjay** [comment]
Whoa, just noticed that https://github.com/dnvriend/akka-persistence-jdbc was overhauled. Would it be fair to say that now, the best idea would be to make a custom DAO to do this?

**Comment by dnvriend** [comment]
The akka-persistence-jdbc-serialization-json project will be closed very soon as it is deprecated. The jdbc plugin has been fully overhauled. Your idea to write a custom DAO seems best, if you want to 'see' the data in the database. You could even write the data dedicated event tables like in the [CounterDao](https://github.com/dnvriend/demo-akka-persistence-jdbc/blob/master/src/main/scala/com/github/dnvriend/dao/CounterJournalDao.scala) example so you can even query the data.

**Comment by dnvriend** [comment]
I have released akka-persistence-jdbc v2.2.18 that can be used as a base for what you want to do. Please take a look at the new [text based serialization formats documentation](https://github.com/dnvriend/akka-persistence-jdbc#text-based-serialization-formats) and the [Base64Serializer](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/serialization/Base64Serializer.scala) for inspiration. Also look at the [configuration](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/test/resources/postgres-varchar-application.conf) how to register a custom text based serializer and bind it to the [new text based daos](https://github.com/dnvriend/akka-persistence-jdbc/tree/master/src/main/scala/akka/persistence/jdbc/dao/varchar). What you want to do is a little bit more complex than the Base64Serializer, but I think you'll have a good base with these ingredients to create a nice JSON serializer. Also you'll need new [schema's](https://github.com/dnvriend/akka-persistence-jdbc/tree/master/src/main/resources/schema/postgres). Good luck!

**Comment by dnvriend** [comment]
For all of your case classes that you want to persist, create JSON serializers and register them. I kinda do this in the [demo project](https://github.com/dnvriend/demo-akka-persistence-jdbc/blob/master/src/main/resources/person-application.conf) in `akka.actor.serializers` and `akka.actor.serialization-bindings`. 

The PersistentRepr that the [text based serializer](https://github.com/dnvriend/akka-persistence-jdbc#text-based-serialization-formats) will receive will contain the serialized case class as a byte array as payload. The case class is JSON but encoded as a byte array. 

So all you'll have to do is write a PersistentRepr serializer that gets the payload which is always a byte array, converts it to a String using UTF-8 encoding and create a wrapper text based format (JSON) that contains the necessary fields. Output that JSON text as a byte array and the text based DAOs will do the rest.

**Comment by acjay** [comment]
Dude, you're a madman! Awesome work! 👏 👏 👏
